# Generated by Django 4.2.9 on 2024-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('salary', models.IntegerField(default=0, null=True)),
                ('image', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
